### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#1423]
#1415 was the latest PR to pass CI

@nikhilwoodruff merged #1416 despite it failing CI, and now all other updates are also failing, e.g. #1422

**Comment by nikhilwoodruff** [comment]
My bad- not sure what happened there. Taking a look now

**Comment by anth-volk** [comment]
Is this closable? Looks like the issue was that #1423 uses an old table schema, whereas the associated tests didn't? Or perhaps I'm wrong.

**Comment by anth-volk** [comment]
I believe this should be fixed with #1426

**Comment by MaxGhenis** [comment]
I just re-ran a [CI job](https://github.com/PolicyEngine/policyengine-api/actions/runs/8725722988/job/24026690455?pr=1429) for updating policyengine-us, now that we've merged #1426, but it's still failing.

**Comment by anth-volk** [comment]
Will look into it

**Comment by anth-volk** [comment]
The problem appears that the old CI runs are using now-deprecated table schemas, so when the tests run against the updated table structures, but utilizing the old schemas, the tests fail, despite the fact that the live code works properly. Would it be possible to test pushing [0.743.1](https://github.com/PolicyEngine/policyengine-api/pull/1435), which was updated after the table updates, and seeing if that works?

**Comment by MaxGhenis** [comment]
#1435, which updated policyengine-us to 0.743.1, was mergeable. Closing.
